######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 12199 2006-11-16 19:28:52Z ska $
##
######################################################################
SUBDIRS =
TARGET  = program
OBJS    = res.o
LDLIBS  = -llessphun -lc

include $(LESSPHUN_BASE)/build/Rules-lessphun.mk
