######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile
##
## $Id: Makefile 2174 2005-03-18 07:00:30Z ska $
##
######################################################################
SUBDIRS   =
LIBS      = ../lib/libmenu.a
HEADERS   = include/menu.h
OBJS      = menu.o
INCLUDES  = -Iinclude -I. -I../utils/include/
DATA_SIZE = 40960

include ../../Rules.mk
