######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 12197 2006-11-16 18:27:24Z ska $
##
######################################################################
SUBDIRS = liblessphun

include $(CIBYL_BASE)/build/Rules-common.mk
