######################################################################
##
## Copyright (C) 2006,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:
##
## $Id:$
##
######################################################################
SUBDIRS=lorminator_dash sokoban sprite_anim

include $(CIBYL_BASE)/build/Rules-common.mk
