######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 13181 2007-01-24 17:20:31Z ska $
##
######################################################################
SUBDIRS = c
RESOURCES=res/program.data.bin res/sprites-x2.png res/tiles-x2.png res/logo.png \
          res/level.0.dat res/level.1.dat res/level.2.dat res/4x6-font.png
TARGET   =src/CompiledProgram.class lorminator-dash.jar lorminator-dash.jad
CIBYL_SYSCALL_SETS ?= resource_manager

include $(CIBYL_BASE)/build/Rules-j2me.mk
