######################################################################
##
## Copyright (C) 2004,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Makefile
##
## $Id: Makefile 608 2004-09-14 18:20:18Z ska $
##
######################################################################
SUBDIRS   =
LIBS      = ../lib/libutils.a
HEADERS   = include/utils.h
OBJS      = utils.o
INCLUDES  = -Iinclude -I.
DATA_SIZE = 40960

include ../../Rules.mk
