######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 12198 2006-11-16 18:30:59Z ska $
##
######################################################################
SUBDIRS = src/
EXTRA_CLEAN=lib/*.a
ALL_TARGETS=

include $(CIBYL_BASE)/build/Rules.mk
