######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 11402 2006-09-30 11:14:55Z ska $
##
######################################################################
SUBDIRS =
TARGET  = program
OBJS    = $(LESSPHUN_BASE)/lib/lessphun.o res.o \
          $(CIBYL_BASE)/lib/crt0.o \
          $(CIBYL_BASE)/lib/ansi.o

include $(LESSPHUN_BASE)/build/Rules-lessphun.mk
